[project]
src = "src"
dot_env = ".env"

[networks.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"

[networks.contracts.coffee]
deployer_script = "script/deploy.py"

[networks.anvil]
url = "http://127.0.0.1:8545"
save_to_db = true
default_account_name = "anvil0"
unsafe_password_file = "~/.moccasin/unsafe-passwords/anvil0"

[networks.sepolia]
url = "$SEPOLIA_RPC_URL"
save_to_db = false
default_account_name = "sepolia_default"
unsafe_password_file = "~/.moccasin/unsafe-passwords/sepolia_default"
explorer_uri = "https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"

[networks.sepolia.contracts.price_feed]
address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"

[networks.sepolia_zksync]
url = "$ZKSYNC_SEPOLIA_RPC_URL"
chain_id = 300
save_to_db = false
default_account_name = "sepolia_default"
unsafe_password_file = "~/.moccasin/unsafe-passwords/sepolia_default"
explorer_uri = "https://explorer.sepolia.era.zksync.dev"
explorer_type = "zksyncexplorer"
is_zksync = true

[networks.sepolia_zksync.contracts.price_feed]
address = "0xfEefF7c3fB57d18C5C6Cdd71e45D2D0b4F9377bF"

[networks.tenderly-sepolia]
url = "$TENDERLY_SEPOLIA_RPC_URL"
chain_id = 111555111
save_to_db = false
default_account_name = "tenderly_account0"
unsafe_password_file = "~/.moccasin/unsafe-passwords/tenderly_account0"

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
